# -*- coding: utf-8 -*-
"""Father-business.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBjk8zlZmHOZ6xR1na6TX6-LNItHkrDr
"""

class Father:
  def __init__(self, name, business_name, capital):
    self.name = name
    self.business_name = business_name
    self.capital= capital

  def info(self):
    print("Name:", self.name)
    print("Business_name:", self.business_name)
    print("Capital:", self.capital)

class Son1(Father):
  def manage_business(self):
    print("Son managing the clothing business")


class Son2(Father):
  def manage_accounts(self):
    print("Son managing the accounts of clothing business")


class Daughter(Father):
  def manage_marketing(self):
    print("Son manages marketing")



print("Son1:")
s1 = Son1("Ahmad"," LHR clothing store", 5000000)
s1.info()
s1.manage_business()
print("------------------------")

print("Son2:")
s2 = Son2("Hakan"," LHR clothing store", 5000000)
s2.info()
s2.manage_accounts()
print("------------------------")

print("Daughter:")
d1 = Daughter("Alena"," LHR clothing store", 5000000)
d1.info()
d1.manage_marketing()
print("------------------------")